//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Otomasyonu.NtpOdevApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneContext : DbContext
    {
        public KutuphaneContext()
            : base("name=KutuphaneContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblKitap> tblKitap { get; set; }
        public virtual DbSet<tblTur> tblTur { get; set; }
        public virtual DbSet<tblUye> tblUye { get; set; }
        public virtual DbSet<tblYazar> tblYazar { get; set; }
        public virtual DbSet<tblUyeKitap> tblUyeKitap { get; set; }
    }
}
