//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Otomasyonu.NtpOdevApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKitap()
        {
            this.tblUyeKitap = new HashSet<tblUyeKitap>();
        }
    
        public int kitapID { get; set; }
        public string kitapAd { get; set; }
        public int kitapYazarID { get; set; }
        public int kitapTurID { get; set; }
        public bool kitapVerildiMi { get; set; }
    
        public virtual tblTur tblTur { get; set; }
        public virtual tblYazar tblYazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUyeKitap> tblUyeKitap { get; set; }
    }
}
