//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Otomasyonu.NtpOdevApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUyeKitap
    {
        public int KitapID { get; set; }
        public int UyeID { get; set; }
        public System.DateTime VerilisTarihi { get; set; }
    
        public virtual tblKitap tblKitap { get; set; }
        public virtual tblUye tblUye { get; set; }
    }
}
